### ISSUE TITLE
Update deprecated ExternalStorage function on sample activity

### ISSUE THREAD

**Issue by irfano** [wordpress-mobile/AztecEditor-Android#1036]
[getExternalStoragePublicDirectory()](https://developer.android.com/reference/android/os/Environment#getExternalStoragePublicDirectory(java.lang.String)) function was deprecated in API level 29. Its usage in MainActivity should be updated.

https://github.com/wordpress-mobile/AztecEditor-Android/blob/bfadd9f7456c8f1465c561daa178c83a4e75ec79/app/src/main/kotlin/org/wordpress/aztec/demo/MainActivity.kt#L654

**Comment by ravishanker** [comment]
PR #1040
