### ISSUE TITLE
Support for most common shortcodes

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/AztecEditor-Android#17]
We should support basic shortcodes: `[caption]` for instance.

This feature should be implemented in a form of a [plugin](https://github.com/wordpress-mobile/AztecEditor-Android/issues/331).

**Comment by rachelmcr** [comment]
+1 to this. Most shortcode support is just a nice-to-have for me, but I definitely expected captions to be supported (especially when captions can be added to images in-app).

**Comment by 0nko** [comment]
Changing to high priority because it's blocking [WP galleries support](https://github.com/wordpress-mobile/WordPress-Android/issues/5749).

**Comment by 0nko** [comment]
Resolved by #436.
