### ISSUE TITLE
Attribute Text in Source View is Clipped and Not Wrapped

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/AztecEditor-Android#214]
### Expected
All text is wrapped to padding.

### Observed
Attributes text in the source view is clipped and not wrapped to the view padding.  See the screenshot below for example.

![clipped](https://cloud.githubusercontent.com/assets/3827611/22394130/b5638d76-e4d4-11e6-9d12-04f6fde388da.png)

### Reproduced
1. Run demonstration app.
2. Tap ***HTML*** format button.
3. Notice `src` attribute value in `img` tag is clipped.
4. Notice `href` attribute value in `a` tag is clipped.

#### Note
The text in the screenshot above was wrapped due to the `/` and `-` characters.  Entering only alphanumeric characters causes the text to never wrap.

#### Tested
Google Pixel on Android 7.1.1 with AztecDemo 1.0

**Comment by hypest** [comment]
Seems that the `EditText` has a problem with monospace fonts. OTOH, `TextView` doesn't seem to have the same wrapping problem. Tried it with a "clean" EditText from scratch and the problem is there.

**Comment by maxme** [comment]
Note: this works fine in wpandroid.

**Comment by 0nko** [comment]
Cannot reproduce anymore in the demo app either.
