### ISSUE TITLE
Can't remove styling when writing text

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/AztecEditor-Android#237]
### Expected
To be able to remove strikethrough and keep writing in "plain" mode.

### Observed
https://cloudup.com/cQCMPkCJvZ2

### Reproduced
1. Write some text. 
2. Apply strikethrough and write some text.
3. Remove strikethrough, and wait a bit.
4. Continue to write without clicking on the space bar.
5. New text has still the strikethrough applied to it.

If you use the backspace char, as soon as type on it, the strikethrough is highlighted in the button bar. Also noticed that the first character is not deleted.

#### Tested
Nexus 5X on 7.1.1 with Integration Branch

**Comment by theck13** [comment]
This is related to suggestions.  Adding `android:inputType="textNoSuggestions"` to the [`AztecText`](https://github.com/wordpress-mobile/WordPress-Aztec-Android/blob/develop/app/src/main/res/layout/activity_main.xml#L26) view eliminates the issue.
