### ISSUE TITLE
Support correct image alignment and text wrapping

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/AztecEditor-Android#257]
### Expected

In Calypso web, when you change an image's alignment you see that alignment (and text-wrapping, when applicable) reflected in the editor:

![screen shot 2017-02-15 at 7 32 55 pm](https://cloud.githubusercontent.com/assets/8658164/22993150/db6cb5d0-f3b9-11e6-898e-152208c4517c.png)

Ideally Aztec would support the same behavior.

### Observed

Aztec currently always aligns the image to the left and wraps the first line of text instead:

![2017-02-15 19 35 28](https://cloud.githubusercontent.com/assets/8658164/22993166/ebf132d2-f3b9-11e6-8b3b-79d5e0e4b16e.png)

### Reproduced
1. Create a post at https://wordpress.com/post on the web.
2. Add text and photos to the post.
3. Make the images thumbnail-sized (this helps see the alignment).
4. Try aligning the photos left, center, and right.
5. Open the same post in Aztec and compare the alignment and text-wrapping.

#### Tested
Tested on Nexus 9, Android 7.1.1, WPAndroid alpha-35

**Comment by ChrissiePollock** [comment]
Internal request for this in #209694-h

**Comment by 0nko** [comment]
Any image is always placed on a separate line due to various problems (#525). Therefore, there is no text wrapping.
