### ISSUE TITLE
Support for copy/pasting of formatted text

### ISSUE THREAD

**Issue by 0nko** [wordpress-mobile/AztecEditor-Android#285]
Add support for for copy/pasting of formatted (such as newlines) text outside the Aztec editor (from Simplenote, for instance). Currently the text is pasted as one large paragraph, even if the original text was split up.

**Comment by annezazu** [comment]
Related: User in 204077-hs suggested adding the ability to clear out formatting after pasting from Word.

**Comment by 0nko** [comment]
Fixed in #454.
