### ISSUE TITLE
Applying quote to paragraph introduces empty <p>s

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/AztecEditor-Android#304]
### Expected
Paragraph tags (`<p>`) should be replaced by the quote tags when applying quotes to the whole paragraph.

### Observed
Empty paragraphs are left around the quote.

### Reproduced
1. Tap ***HTML*** format button
2. Enter `<p>hello</p>`
3. Tap ***HTML*** format button
4. Tap the Quotes format button
6. Tap ***HTML*** format button to switch back to HTML mode
7. Notice that there are 2 pairs of extra `<p></p>`, one before and the other after the blockquote

#### Tested
Nexus 5X on Android v7.1.1

**Comment by hypest** [comment]
Root cause of this issue is that the `tidy()` phase of the conversion to html does not allow block elements inside `<p>`s.

**Comment by 0nko** [comment]
Can't reproduce anymore.
