### ISSUE TITLE
Text disappearing when deleting paragraphs

### ISSUE THREAD

**Issue by 0nko** [wordpress-mobile/AztecEditor-Android#337]
When I delete all the way to the start of a paragraph, paragraphs above it go missing and generally get weird. Here’s what I did:

1. Create seven paragraphs of text.
2. Delete all the text in the seventh paragraph.
3. Result: When I hit the beginning of the seventh paragraph (but before deleting the paragraph break) the fifth paragraph also disappeared.
4. Delete all the text in the sixth paragraph.
5. Result: The fifth paragraph reappeared but the third and fourth disappeared.
6. I continued deleting and paragraphs kept appearing/disappearing.

Edited to add screenshots (in order as I deleted one line at a time):

![image](https://cloud.githubusercontent.com/assets/1522856/25610528/dfaddfb6-2f23-11e7-9c3f-7e5e3f64b672.png)

![image](https://cloud.githubusercontent.com/assets/1522856/25610512/d0e52e62-2f23-11e7-96d8-a7050db9c47c.png)

![image](https://cloud.githubusercontent.com/assets/1522856/25610573/037db6be-2f24-11e7-8e68-c3263d099035.png)

![image](https://cloud.githubusercontent.com/assets/1522856/25610631/4b431fc0-2f24-11e7-85be-bc9f145f6ce9.png)

![image](https://cloud.githubusercontent.com/assets/1522856/25610590/1e027042-2f24-11e7-9a1f-17b00ed53f0c.png)

**Comment by khaykov** [comment]
Fixed in #348
