### ISSUE TITLE
Toggling From HTML View Merges Consecutive Spaces

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/AztecEditor-Android#338]
### Expected
All spaces are retained when toggling between visual and HTML views.

### Observed
Consecutive spaces are merged into a single space when toggling between visual and HTML views.

### Reproduced
1. Enter text with multiple spaces.
2. Tap ***HTML*** format button.
3. Notice multiple spaces are retained.
4. Tap ***HTML*** format button.
5. Notice multiple spaces are merged into a single space.

#### Tested
Google Pixel on Android 7.1.2 with AztecDemo 1.0

**Comment by khaykov** [comment]
After trying for some time to implement it in some way and failing, I found out that this behavior is in HTML spec, and for a good reason. To have a formatted HTML, we need to merge all the spaces (unless in pre tags).

[Relevant discussion on SO](https://stackoverflow.com/questions/433493/why-do-multiple-spaces-in-an-html-file-show-up-as-single-spaces-in-the-browser).

**Comment by maxme** [comment]
HTML specs FTW - closing that one as won't fix
