### ISSUE TITLE
View Scrolls to Cursor When Uploading Image Below Scroll Position

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/AztecEditor-Android#342]
### Expected
View remains at scrolled position when uploading images.

### Observed
View scrolls to the cursor position when uploading images <i>below</i> scroll position, but remains at scrolled position when uploading images <i>above</i>.  See the animation below for example.

![image_uploading_scroll](https://cloud.githubusercontent.com/assets/3827611/26017198/9e051caa-3725-11e7-9b30-433d7da6c54e.gif)

### Reproduced
1. Place cursor near bottom of view.
2. Tap ***Media*** format button.
3. Choose image to insert.
4. Scroll to top of view.
5. Notice view is scrolled to cursor.
6. Place cursor near top of view.
7. Tap ***Media*** format button.
8. Choose image to insert.
9. Scroll to bottom of view.
10. Notice view does not scroll to cursor.

#### Tested
Google Pixel on Android 7.1.2 with AztecDemo 1.0

**Comment by khaykov** [comment]
fixed in #349
