### ISSUE TITLE
Pressing enter before the first line in editor adds newline instead of paragraph

### ISSUE THREAD

**Issue by khaykov** [wordpress-mobile/AztecEditor-Android#350]
### Expected
Pressing enter before the first line in editor adds paragraph before this line

### Observed
Pressing enter before the first line in editor adds newline before this line

### Reproduced
1. Put cursor at the beginning of editor and press enter.
2. Notice that instead of paragraph newline was added before the second line

**Comment by 0nko** [comment]
It only seems to work initially in the visual mode. But in the following scenarios the 1st paragraph is lost:

- 1. Press enter in an empty editor and type something on the 2nd line
  2. Switch to HTML
  3. Notice the 1st (empty) paragraph is gone
- 1. Press enter in an empty editor and type something on the 2nd line
  2. Move cursor to the 1st paragraph and type something
  3. Switch the HTML
  4. Notice the 2 lines are now part of the same paragraph

**Comment by khaykov** [comment]
Hey, @0nko ! Is it a comment for #356?
If so, regarding the first problem - content is trimmed from both sides, so this is expected behavior (same in Calypso). 

The second issue, I tried to reproduce it, but without any luck. 
[![https://gyazo.com/e14cd8b5819be442433c1affa453be75](https://i.gyazo.com/e14cd8b5819be442433c1affa453be75.gif)](https://gyazo.com/e14cd8b5819be442433c1affa453be75)

**Comment by 0nko** [comment]
Oops, sorry, I meant to comment on the PR :P. Let me continue there.
