### ISSUE TITLE
Deleting All Text Containing Inline Style with Backspace Leaves Empty Tags

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/AztecEditor-Android#362]
### Expected
Deleting all text from the visual view using the backspace key deletes all text and formatting from the HTML view.

### Observed
Deleting all text from the visual view using the backspace key leaves empty tags of the inline style(s) applied to the last deleted text.

### Reproduced
1. Enter "none bold none italic none strike" into the demonstration app.
2. Select "bold" text.
3. Tap ***Bold*** format button.
4. Select "italic" text.
5. Tap ***Italic*** format button.
6. Select "strike" text.
7. Tap ***Strike*** format button.
8. Place cursor at end of text.
9. Tap ***Backspace*** key until text is gone.
10. Tap ***HTML*** format button.
11. Notice `<b></b>` tags remain.

#### Tested
Google Pixel on Android 7.1.2 with AztecDemo 1.0

**Comment by khaykov** [comment]
Fixed in #398
