### ISSUE TITLE
Incorrect heading type being selected

### ISSUE THREAD

**Issue by 0nko** [wordpress-mobile/AztecEditor-Android#380]
Heading type of the line above is being selected in the toolbar after applying a list style to some text below a heading.

### Reproduced
1. Launch demonstration app.
2. Move cursor anywhere in "Bold" text.
3. Tap Ordered List or Unordered List format button.
4. Tap Heading format button.
5. Notice **Heading 6** is selected.

**Comment by khaykov** [comment]
Probably same issue as #317

**Comment by 0nko** [comment]
Oh, yeah, probably. Thanks @khaykov!
