### ISSUE TITLE
Uploading an image makes the editor too jumpy - unusable

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/AztecEditor-Android#394]
Possibly related: #313 
First observed by @catehstn 

### Expected
The user should be able to keep writing / editing while an image is being uploaded

### Observed
Instead, it's too jumpy and it's impossible to keep the cursor where you want to write - even tapping on the Title field seems to be losing focus immediately.

Video here:
https://cloudup.com/cJmqh2lK6UK

### Reproduced
1. Start a new draft
2. Pick an image to upload
3. try to write something either in the title or before/after the image

#### Tested
[Google Pixel] on [7.1.2], observed this happening on latest `alpha-61` and `develop` in WPAndroid, and is consistently reproduceable

**Comment by khaykov** [comment]
I have a feeling we fixed it in the demo app (#349) but forgot to do it in wpandroid. 🤦‍♂️

**Comment by khaykov** [comment]
Fixed in #6208
