### ISSUE TITLE
Image overlapping 

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/AztecEditor-Android#410]
### Expected
Uploading images should not overlap

### Observed
Uploading several images overlap each other. Rotating the device sometimes make it appear OK again.

![screenshot_20170711-152515](https://user-images.githubusercontent.com/6597771/28088093-ffaac590-665a-11e7-96c2-dcd441bf9dd7.png)
![screenshot_20170711-152533](https://user-images.githubusercontent.com/6597771/28088094-ffad21be-665a-11e7-8e58-6637cd3b5012.png)
![screenshot_20170711-152609](https://user-images.githubusercontent.com/6597771/28088096-ffb13dee-665a-11e7-8e54-9ea4e9ebbd64.png)

### Reproduced
Couldn't reproduce consistently, but if you upload a couple of different-sized images and start rotating, eventually you get the results.

#### Tested
[Google Pixel] on [7.1.2] with [`feature/async-media` branch in WPAndroid repo]

**Comment by maxme** [comment]
I can repro that one, add a few images, rotate and back. When I close the editor and reopen the same post, everything looks good.

**Comment by daniloercoli** [comment]
Are you able to reproduce this on the Test App? I tried with pictures of different sizes but wasn't able to repro in the test app. Tried with pictures smaller than the viewport.

**Comment by 0nko** [comment]
Since the images are now always put on separate lines (introduces with #525), this has become a non-issue.

**Comment by maxme** [comment]
Reopening this one as it is still happening after an orientation changes.

**Comment by maxme** [comment]
This is not an Aztec bug, but a `EditPostActivity` issue in wpandroid. We should remove the `configChanges` for this activity in the AndroidManifest
