### ISSUE TITLE
EditText trying to show image objects when in landscape

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/AztecEditor-Android#412]
### Expected
Rotating the device to landscape should just rotate the screen

### Observed
The edit text field goes full screen and if you have images you see `obj` objects representing them

![screenshot_20170712-114643](https://user-images.githubusercontent.com/6597771/28126614-59bc6f52-6700-11e7-83dc-810b72dbe737.png)

### Reproduced
1. open a new draft
2. include a couple of images
3. while having the cursor in the post body area, rotate the device

#### Tested
[Goole Pixel] on [7.1.2] with [7.7]

**Comment by khaykov** [comment]
I think it is related to [this](https://github.com/wordpress-mobile/WordPress-Android/pull/5073) open PR in wpandroid.
