### ISSUE TITLE
Out of bound in AztecMediaSpan -> setOverlayLevel

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/AztecEditor-Android#422]
### Expected
`setOverlayLevel` in `AztecMediaSpan` doesn't check if the passed index is valid or not.

Ref: https://github.com/wordpress-mobile/WordPress-Android/issues/6346

<del>Note: not sure if we need to fix this first in `beta4`,  and then in `develop` since `wp-android` seems to use the `v1.0-beta.4`.</del>

**Comment by 0nko** [comment]
Fixed by #423.
