### ISSUE TITLE
History not reliable

### ISSUE THREAD

**Issue by 0nko** [wordpress-mobile/AztecEditor-Android#445]
The history does not work reliably (undo, redo does not bring back the right state) for:

- Copy/pasting 
- Adding newlines inside blockquotes
- Deleting of empty list items with a backspace
- Adding an image, pressing undo, then redo (does not bring the image back)
- Deleting the demo text, then undoing loses all styling

We need unit tests for all the different scenarios of using the history.

A nice feature would be to be able to define a timeout and only save after X seconds of inactivity, as opposed to after every key stroke.

**Comment by maxme** [comment]
I de-prioritized this issue for now. We can eventually ship Aztec v1 without undo/redo since the Hybrid editor doesn't have it.
