### ISSUE TITLE
Text alignment support

### ISSUE THREAD

**Issue by 0nko** [wordpress-mobile/AztecEditor-Android#465]
Support left, center and right alignment of paragraphs.

Related iOS issue: https://github.com/wordpress-mobile/AztecEditor-iOS/issues/649

**Comment by ChrissiePollock** [comment]
This was requested again in internal issue #217678-h

**Comment by ChrissiePollock** [comment]
requested again in #238383-h

**Comment by ChrissiePollock** [comment]
and again #238453-h

**Comment by SiobhyB** [comment]
This was requested again in 256661-h.

**Comment by daniloercoli** [comment]
Addressed in #624.
