### ISSUE TITLE
Update 'Beta' label in editor to 'Feedback'

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/AztecEditor-Android#473]
Due to an iOS App Store issue, we had to change the `Beta` label/button on the editor to something else, and it was decided that it'd be changed to `Feedback`. This is probably a better option, so we should consider making this change on Android as well. 

### Reproduced
1. Open a new or existing post
2. See `Beta` label/button along right side of title area

![1b8485ed-b518-4b39-a91a-050909d37a65](https://user-images.githubusercontent.com/1200432/29883308-8572ff62-8d75-11e7-92be-953c3d85b7f1.jpg)

**Comment by 0nko** [comment]
I think that title would be a bit misleading, since you can't really give feedback there. What about "What' new"?

**Comment by mzorz** [comment]
> I think that title would be a bit misleading, since you can't really give feedback there. 

I was thinking the same, what's the reasoning behind naming this button "Feedback" @iamthomasbishop ?

**Comment by 0nko** [comment]
@iamthomasbishop Is this issue still relevant or has there been any update?

**Comment by iamthomasbishop** [comment]
@0nko - @elibud came across an issue where the translated label can be very long in some languages, so we are considering changing the text label to an icon. The icon that makes sense at this point is probably the `?` icon. Here's what it looks like (`gridicons-help-outline` set in $gray color):

<img width="506" alt="screenshot 2017-09-29 10 49 13" src="https://user-images.githubusercontent.com/1200432/31024204-ef7b9266-a503-11e7-9e28-ee78a16e9bd4.png">

Note: this label will be gone in a couple weeks when Aztec becomes the default editor.

**Comment by 0nko** [comment]
OK, cool 👍

**Comment by 0nko** [comment]
This is actually a WP-specific issue. I'll recreate it there.
