### ISSUE TITLE
Add a gap between adjacent images

### ISSUE THREAD

**Issue by khaykov** [wordpress-mobile/AztecEditor-Android#492]
We should add a 1 dp gap between adjacent images to make it clear which image is targeted by the loader.

**Comment by maxme** [comment]
We should probably add a bigger gap between images (or allow it to be configured by the app) so the user can move it's cursor between images.

**Comment by folletto** [comment]
> We should probably add a bigger gap between images (or allow it to be configured by the app) so the user can move it's cursor between images.

Expanding this from a interaction modelling perspective:

1. The text cursor shows either to the left (vertical bar full height with the image), to the right, or selects the image (the whole image should get something like a border of the same color of the cursor).
2. The cursor should never show in between (so, 1px is fine) unless there's a line in between, in which case, the cursor will show as normally on a blank line
3. In this general model, there's no discernible difference (unfortunately) between two images on the same line that happen to wrap, and two images on two different lines. We could however make this more evident by playing with margins: 1px if they are both on the same line and just happen to wrap, while somewhere between 1px and a 1em (single text line height) when they are on separate lines. While this might follow the same difference between line wrap and paragraph spacing, it might require still a special case to sharpen the difference between same-line, multi-line and line-in-between.

**Comment by daniloercoli** [comment]
Fixed in #525
