### ISSUE TITLE
Missing space 

### ISSUE THREAD

**Issue by liufsd** [wordpress-mobile/AztecEditor-Android#515]
test :
```a            nn   ccc   899999```

it will only show : 
```a nn ccc 899999```

it will missing whitespaces by '  builder.append(parser.fromHtml(cleanSource, context))'

**Comment by maxme** [comment]
Can you give us more details? I'm not sure to understand what's the issue?

**Comment by maxme** [comment]
This is actually a duplicate of https://github.com/wordpress-mobile/AztecEditor-Android/issues/338
