### ISSUE TITLE
Lost intra-word Italic and bold font formatting

### ISSUE THREAD

**Issue by AmandaRiu** [wordpress-mobile/AztecEditor-Android#517]
### Expected
Toggling bold or italic should apply to only newly typed characters and not affect previously typed characters.  

### Observed
Different observations across different APIs. 

**Version 1 - The second toggle**
API 26 (emulator tested only)
Applying bold or italic font formatting in the middle of a word works fine, but toggling it off will revert the formatting for the entire word _after entering two additional characters._ 

**Version 2 - The instant revert**
Samsung Galaxy S6 API 24 
Applying bold or italic font formatting in the middle of a word will instantly revert that formatting as you type. 
Video of experience: 

### Reproduced
**Version 1:**
1. Start the demo app
2. In the Rich Text Editor, enter "some"
3. Toggle bold on, enter "more"
4. Toggle bold off, enter "t" - notice how the formatting is still applied properly
5. Type "e" - the formatting is immediately reverted

**Version 2:**
1. Start the demo app
2. In the Rich Text Editor, enter "some"
3. Start typing, the formatting will be reverted as you type

#### Tested
**No issues found:**
Nexus 5 Emulator on API 19
Nexus 7 (2012) Emulator on API 21 

**Version 1 issue:**
Nexus 5x Emulator on API 26 
Google Pixel XL on API 27
HTC Nexus 9 on API 25

**Version 2 issue:**
Samsung Galaxy S6 on API 24

**Comment by maxme** [comment]
This should be hopefully be fixed via https://github.com/wordpress-mobile/AztecEditor-Android/issues/555 🤞

**Comment by mzorz** [comment]
Closing as not observing it anymore, following steps indicated above
