### ISSUE TITLE
Content appears all in one line

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/AztecEditor-Android#529]
First reported in https://github.com/wordpress-mobile/AztecEditor-Android/pull/466#issuecomment-344315573

### Expected
Content should correctly handle new lines

### Observed
Content appears all in one line
![aztec_horizontal](https://user-images.githubusercontent.com/6597771/32791440-b87446c0-c969-11e7-84f5-b59d00b7ba36.gif)

### Reproduced
On a Geny image of Samsung Galaxy S3, Android 4.2.2, run the Aztec demo app and observe the behavior shown in the image: there are no newlines ,it seems everything is on the same line

#### Tested
[Samsung Galaxy S3] on [Android 4.2.2] with [develop]

**Comment by 0nko** [comment]
I've tested the `develop` branch with other APIs and it's also happening on API 16 and 17. After some more testing I found that this problem was introduced with the fixing spellcheck PR (#476).
