### ISSUE TITLE
Formatting disappears when inserting space before formatted text

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/AztecEditor-Android#530]
Originally reported in https://github.com/wordpress-mobile/AztecEditor-Android/pull/466#issuecomment-338112619

### Expected
Formatting should always be respected

### Observed
Formatting is lost for the text to the right of an inserted space

### Reproduced

1. on the editor, type "a" 
2. toggle Bold style, 
3. type "b". 
4. Put the cursor between "a" and "b" 
5. press space. Notice that "b" became unstyled.

#### Tested
[Google Pixel] on [Android 8] with [develop Aztec demo app]
tested on API 22 5.1.0, issue not observed
tested on API 17 4.2.2, issue not observed

**Comment by mzorz** [comment]
Another problem found with the LEFT-RIGHT keys, only observed in 4.2.2:
- entering a, then bold, then b, then tapping LEFT jumps 2 positions instead of just 1.
- entering, a, b, c, then selecting text then moving selector to only keep “c” selected, tapping B(old), then move the left/right keys from the keypad, note that you can only navigate between a and b, but when you are here `ab|c` and tap RIGHT to go to the right of letter “c” the cursor moves to the LEFT!!, showing like this `a|bc`.

When testing on API 26 (Android 8.0) ,it works alright (it jumps only 1 position at a time).

**Comment by mzorz** [comment]
Separating https://github.com/wordpress-mobile/AztecEditor-Android/issues/530#issuecomment-345221754 into a new issue #538

**Comment by rachelmcr** [comment]
Noting that this is also an issue in related cases (not only when a space is added before formatted text).

Formatting disappears when a space is added in the middle of formatted text:

1. In the editor, toggle bold style
2. Type "ab"
3. Place cursor between "a" and "b"
4. Add a space
5. Note that the bold formatting is removed from all text

Formatting disappears when a space is added after formatted text ends:

1. In the editor, toggle bold style
2. Type "a"
3. Toggle bold style (off)
4. Type "b"
5. Place cursor between "a" and "b"
6. Add a space
7. Note that the bold formatting is removed

**Comment by maxme** [comment]
This should be fixed via https://github.com/wordpress-mobile/AztecEditor-Android/issues/555

**Comment by daniloercoli** [comment]
I can reproduce this issue on API25:
- In the editor
- Type "a"
- Toggle bold style
- Type "b"
- Place cursor between "a" and "b"
- Add a space
- Note that the bold formatting is removed
