### ISSUE TITLE
Improve output message for failing UI tests

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/AztecEditor-Android#531]
As requested in https://github.com/wordpress-mobile/AztecEditor-Android/pull/521#issuecomment-344912682:

> [...] do you mind implementing describeMismatchSafely in the Matchers (or maybe use TypeSafeDiagnosingMatcher, I'm not familiar with Harmcrest) to change the output of failing tests? It's hard to read the current output with the full view dump:
> 
> ```
> AssertionFailedWithCauseError: 'EditText matches hello world' doesn't match the selected view.
> Expected: EditText matches hello world
> Got: "SourceViewEditText{id=2131231019, res-name=source, visibility=VISIBLE, width=768, height=928, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=true, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@f80d919, tag=null, root-is-layout-requested=false, has-input-connection=true, editor-info=[inputType=0xa0001 imeOptions=0x58000005 privateImeOptions=null actionLabel=null actionId=0 initialSelStart=0 initialSelEnd=0 initialCapsMode=0x0 hintText=Codex is the source label=null packageName=null fieldId=0 fieldName=null extras=null hintLocales=null contentMimeTypes=null ], x=0.0, y=0.0, text=bye bye world, hint=Codex is the source, input-type=655361, ime-target=true, has-links=false}"
> ```
> 
> It would be great if we could get this instead:
> 
> ```
> AssertionFailedWithCauseError: 'EditText matches hello world' doesn't match the selected view.
> Expected: "hello world"
> Got: "bye bye world"
> ```

**Comment by rachelmcr** [comment]
I investigated this further, and it turns out that Espresso bypasses `describeMismatchSafely` and [implements its own output for view matchers](https://android.googlesource.com/platform/frameworks/testing/+/android-support-test/espresso/core/src/main/java/android/support/test/espresso/matcher/ViewMatchers.java?autodive=0%2F%2F#996), which is where the dump of the view properties comes from.

It looks like we're stuck with this output for now, although there's an open issue about this for Espresso: https://issuetracker.google.com/issues/37136496

cc @maxme

**Comment by maxme** [comment]
Thanks for looking into this, I stared this issue in the Google tracker.
