### ISSUE TITLE
Cursor can not move the text end after Insert a image between text.

### ISSUE THREAD

**Issue by liufsd** [wordpress-mobile/AztecEditor-Android#535]
### Expected

insert a image between text. and then the cursor can move to the sub text end.

this issue: https://github.com/wordpress-mobile/AztecEditor-Android/issues/513 just fix the 'Caption'. but not fix this issue.

video here:

https://cloudup.com/cHbUVADDY8t

**Comment by 0nko** [comment]
Thanks for the video. I'll look into it.
