### ISSUE TITLE
Style lost when adding a new line before formatted text

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/AztecEditor-Android#567]
### Expected

I expect to be able to place the cursor at the start of formatted text and press enter to move the formatted text to a new line, without affecting the formatting.

### Observed

Block elements:

When I place the cursor at the beginning of a block element (heading, list, quote) and press enter, the formatting is removed and no new line is added. Instead, the cursor moves forward one character.

Other formatting:

When I place the cursor at the beginning of the formatted text (e.g. bold, italic) and press enter, a new line is added but it also removes the formatting.

### Reproduced

Block elements:

1. In the demo app, enable a block formatting style (e.g. the "Heading 1" style).
2. Enter text (e.g. the letter "a").
3. Place the cursor at the beginning of the line.
4. Press enter.

Result: The style is removed and the cursor moves one character to the right (after the "a").

Non-block elements:

1. In the demo app, enable a regular formatting style (e.g. the bold style).
2. Enter text (e.g. the letter "a").
3. Place the cursor at the beginning of the line.
4. Press enter.

Result: A new line is added but the style is removed from the text.

#### Tested
Nexus 9 on Android 7.1.1 with develop

**Comment by daniloercoli** [comment]
> When I place the cursor at the beginning of a block element (heading, list, quote) and press enter, the formatting is removed and no new line is added. Instead, the cursor moves forward one character.

I was not able to reproduce the issue by using the demo app with the "pre-filled" content.
Instead I was able to reproduce the issue starting AztecDemo with empty content or by erasing all the pre-filled demo content before trying to replicate the issue.

Steps to repro in `develop`:
- Start the demo app with empty content
- Or just start the demo app and `select all` + `cut` over the pre-filled content.
- Choose H1 from toolbar and insert some text
- Move the cursor at the beginning of the text and tap enter
- The style is removed and the cursor moves one character to the right
 
_The same problem appears if you add more lines with styles and then move the cursor at the beginning of one of those and tap enter. So it's not a matter of the position of the line in the editor._
