### ISSUE TITLE
Paste as Plain Text should remove formatting from the pasted text

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/AztecEditor-Android#653]
On Android 8, there is a new feature to paste formatted text as plain text:

1. Select formatted text (a title for example).
2. Long Press
3. Tap ...
4. Select `Past as Plain Text`

**Comment by iamthomasbishop** [comment]
Related to this iOS issue: https://github.com/wordpress-mobile/AztecEditor-iOS/issues/1028

We have decided to change the label of this option to `Paste without Formatting`, and like this issue it should also remove styling from the pasted contents. Whether it also removes links is under consideration.

**Comment by mzorz** [comment]
Closed via #739
