### ISSUE TITLE
html not contains <p>

### ISSUE THREAD

**Issue by nierongcheng** [wordpress-mobile/AztecEditor-Android#655]
**iOS version has p tag, will android support this?**

![image](https://user-images.githubusercontent.com/3412717/39119782-4ff4c5dc-471f-11e8-89a4-e8eabde27407.png)

**Comment by nierongcheng** [comment]
iOS version has p tag, will android support this?

**Comment by 0nko** [comment]
Aztec Android already supports this. You just need to turn off the Calypso mode:
```
aztecText.setCalypsoMode(false); 
sourceText.setCalypsoMode(false);
```

**Comment by nierongcheng** [comment]
@0nko Hi 0nko, I download the library from master and run the demo, then click the source button, still not contains p tag.

**Comment by 0nko** [comment]
There is no `<p>` in the demo text, but you definitely use it.
