### ISSUE TITLE
[Aztec + GB] Properly handle new lines at end of blocks

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/AztecEditor-Android#659]
Noticed that GB posts can be easily broken if you edit a post by adding new lines at the end of a block.
The web interface notice the error, and propose a fix, but we should make sure to remember the "GB closing comment" position when exiting a block. (2 new lines).

Steps to repro:
- Open a GB block with a `pre-formatted` block in it.
- Tap at the end of the block, and tap `enter` twice to exit the preformatted block.
- Add new content.
- Ended up with the following content:
```
<!-- wp:preformatted -->
<pre class="wp-block-preformatted">Preformatted block content</pre>
<br>
<br>
Hello There,
<br>
Look at the sky, it's falling!
<br>
<!-- /wp:preformatted --> <!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph -->
```

**Comment by koke** [comment]
Opening an issue for Gutenberg to be a bit more liberal in what it accepts is also possible 😉

**Comment by daniloercoli** [comment]
> I’m torn about this issue because technically Aztec is dealing with HTML just fine

Not quite sure I got this right. Aztec with the GB plugin is not a default HTML editor.  It already hides GB comments on purpose with no ability for the user of changing them.

> Maybe the solution to this can be written through an Aztec plugin? 

Yes, I think we should implement this in the current Gutenberg plugin for Aztec. That plugins already hides comments, it "just" needs to remember to put it back in the right place. Without the needing of entering in details implementation of GB. Just put what you've hidden back in the right position.
OFC I said this in simple words, maybe it's not a viable solution when we look deeper at code.
