### ISSUE TITLE
Nested block can add a new empty paragraph after it

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/AztecEditor-Android#688]
This was original reported for GB [here](https://github.com/wordpress-mobile/AztecEditor-Android/issues/686#issuecomment-393159018), but turned out to be a more general problem with the way Aztec handles nested block with paragraphs.

### Steps to repro
Start the demo app with the following content
```
<div>
 <p>first paragraph</p>
</div>
<p>second par</p>
```
Then switch the demo app to HTML mode.
The output is the following
```
<div>
 <p>first paragraph</p>
</div>
<p></p>
<p>second par</p>
```

As you can see there is a new `p` element in between those 2 original 1st level element.

**Comment by daniloercoli** [comment]
It seems to me that this issue is due to a problem in the `AztecParser`. 
When you feed Aztec with the demo content reported above, the internal parser in [fromHtml:L64](https://github.com/wordpress-mobile/AztecEditor-Android/blob/develop/aztec/src/main/kotlin/org/wordpress/aztec/AztecParser.kt#L64)
returns the following Spannable:

```
<-------------->                 000 -> 015 : HiddenHtmlSpan
<-------------->                 000 -> 015 : ParagraphSpan
               <--------->       015 -> 025 : ParagraphSpan
```

Immediately after, when `addVisualNewlinesToBlockElements` returns the Spannable has the following structure:

```

first paragraph¶second par  length = 26
<-------------->                  000 -> 015 : HiddenHtmlSpan
<--------------->                 000 -> 016 : ParagraphSpan
                <--------->       016 -> 026 : ParagraphSpan
               >                   015 -> 015 : AztecVisualLinebreak

```

It seems to me that the "outer" HiddenHtmlSpan was not expanded to include the new line just added.

cc @0nko since you may have a quick fix for this.

**Comment by 0nko** [comment]
I think I've seen this before but I thought it's been fixed. 

> The "outer" HiddenHtmlSpan was not expanded to include the new line just added.

This is probably the culprit. I'm going to take a look if I can come up with something.
