### ISSUE TITLE
Aztec should produce valid HTML document

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/AztecEditor-Android#691]
### Expected
* Valid HTML document displayed in the HTML editor.
* valid HTML document returned by both the Visual Editor (`ztecText.kt` method `toHTML`) and and HTML editor (`SourceViewEditText.kt` method `getPureHtml`) 

### Observed
If you start the demo app with valid HTML document like the following

```
<!-- wp:audio {"id":40} -->
<figure class="wp-block-audio"><audio controls src="your-content.mp3"></audio></figure>
<!-- /wp:audio -->
```
Then switch to HTML and you will see:

```
<!-- wp:audio {"id":40} -->
<figure class="wp-block-audio"><audio controls src="your-content.mp3" /></figure>
<!-- /wp:audio -->
```
The `audio` tag is replaced by a self-closing audio tag. That's outside the HTML specs. 
 ref: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio

### Observed
There are basically 2 problems there, the function that formats the input to be displayed on the screen doesn't set Jsoup to produce HTML.
The 2 methods (one in the Visual editor and one in the HTML editor) that return the HTML are not invoking Jsoup, so there is the possibility, especially for the visual editor to get back unexpected HTML code. 

### Note
Since this would be a rather big change, we've agreed on fixing the problem with `audio` tag with a regexp (a PR is coming for it), and postpone the full fix to another PR with better testing.

For reference the first PR that should fixe it, once and for all, is available here: https://github.com/wordpress-mobile/AztecEditor-Android/pull/690

**Comment by hypest** [comment]
Fixed by #692
