### ISSUE TITLE
GB end-delimiters (html comment closing tags) are not preserved in the correct position

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/AztecEditor-Android#717]
Basically making some edits to a block could result in the GB hidden closing tag not staying attached to the correct HTML tag.

For pre-formatted block, just add more text to it, and then double tap to exit the block. 
For paragraph block, tap on it and insert a new element from the toolbar.  
Details below:

**Paragraph block --> adding new Heading from toolbar**
- Feed the demo app with a simple GB block
`<p class="has-background has-vivid-red-background-color" style="font-size: 49px">This is a test.</p>
`
- Put the cursor at the end of the text, tap enter and insert new rows
- The paragraph is correctly working with GB (check the HTML)
- Now put the cursor at the end of the paragraph and insert one of the `Heading`s from the toolbar
- Resulting document: 
```
<!-- wp:paragraph {"backgroundColor":"vivid red","customFontSize":49} -->
<p class="has-background has-vivid-red-background-color" style="font-size:49px">This is a test.<br>
and<br>
this<br>
is<br>
a<br>
test.</p>
<h1>H1 text</h1>
<p></p>
<!-- /wp:paragraph -->
```
 As you can see the new heading GB delimiters are not attached to the original `p ` tag.

**Preformatted block --> adding new lines**
- Create a new pre-formatted GB block
`<!-- wp:preformatted --><pre class="wp-block-preformatted">this is<br>pre<br>formatted</pre><!-- /wp:preformatted -->`
- Open it in the app, put the cursor at the end of the block, add some words.
- Double enter to exit the block, and add more content to the document.
- Resulting HTML
`<!-- wp:preformatted --><pre class="wp-block-preformatted">this is<br>pre<br>formatted<br>add1<br>add2</pre><br>Lollipop!<!-- /wp:preformatted -->`

The `<!-- /wp:preformatted -->` closing element is not preserved attached to the `pre` tag.

Opening those tests in GB will result in broken block dialog

**Comment by hypest** [comment]
Tried the 2 cases in https://testgutenberg.com (Gutenberg v3.0.1) and it seems that the first one (paragraph engulfing headings) is not breaking the GB editing experience while the second (preformatted block new lines) does. I'd suggest we split the cases into separate tickets @daniloercoli , wdyt?

**Comment by daniloercoli** [comment]
We can split it in 2 tickets, even though it's more a general problem that affects GB hidden comments rather than a problem with `pre`.
I didn't test other blocks, but I think it will be very simple to break them just adding a single new line of text after those.

In any case feel free to split it, and I will open new tickets while i'm testing other blocks with the same testing steps.

**Comment by hypest** [comment]
I think that some blocks will normally allow more "stuff" to be added in them (even as child blocks) but others will get broken, and in that sense it seems to me that "sticking" the GB comment delimiters to their original neighboring elements is not desirable.

Perhaps even the current situation where the block delim SPAN just expands will prove undesirable, and that's why I think this needs to be tackled in a case by case manner.

I will create a new ticket to harbor the `<pre>` case 👍

**Comment by hypest** [comment]
> Now put the cursor at the end of the paragraph and insert one of the Headings from the toolbar

I think that's too advanced editing for Aztec to handle without becoming too aware of GB so, closing this as `wontfix` and `too-gb-aware`.
