### ISSUE TITLE
Adding lines to a <pre> block breaks GB editing

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/AztecEditor-Android#720]
(Extracted from #717 to isolate the `<pre>` case)

When adding new lines and exiting a `<pre>` element causes Gutenberg to display the "This block appears to have been modified externally." placeholder.

#### Steps to reproduce:

- Create a new pre-formatted GB block
`<!-- wp:preformatted --><pre class="wp-block-preformatted">this is<br>pre<br>formatted</pre><!-- /wp:preformatted -->`
- Open it in the app, put the cursor at the end of the block, add some words.
- Double enter to exit the block, and add more content to the document.
- Resulting HTML
`<!-- wp:preformatted --><pre class="wp-block-preformatted">this is<br>pre<br>formatted<br>add1<br>add2</pre><br>Lollipop!<!-- /wp:preformatted -->`

**Comment by koke** [comment]
After you hit "Convert to Blocks" it looks fine to me:

![screen shot 2018-06-20 at 10 19 20](https://user-images.githubusercontent.com/8739/41646196-718ecb76-7473-11e8-994a-38752c105e52.png)

I'd be happy dropping this one

**Comment by hypest** [comment]
> I'd be happy dropping this one

Agreed. The fix will require Aztec to become more aware of the GB blocks way of editing.

Closing this with `wontfix` and `too-gb-aware` labels.
