### ISSUE TITLE
Adding lines after a List block may break GB editing

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/AztecEditor-Android#722]
Editing a post that has a list block in Aztec by adding more content after the list can cause Gutenberg to display the "This block appears to have been modified externally." placeholder.

(GB seems to be able to recover from it, even though you need to manually tap to "convert to block" button).

Steps to reproduce:
- Create a new list GB block
`<!-- wp:list --><ul><li>Item 1</li><li>Item 2</li></ul><!-- /wp:list -->`
- Open it in the app
- Try to add new content after the list 
- (In this case I placed the cursor on the last item and tapped enter twice to exit the block)
- Add some words

Alternatively you can add one more item to the list, and then tap enter twice to exit the list block.

Resulting HTML
```
<!-- wp:list -->
<ul>
 <li>Item 1</li>
 <li>Item 2</li>
</ul>This is new content.
<!-- /wp:list -->
```

**Comment by koke** [comment]
Convert to blocks seems to recover fine:

![screen shot 2018-06-20 at 16 51 16](https://user-images.githubusercontent.com/8739/41666194-31820836-74aa-11e8-8111-add879c1cf2b.png)

**Comment by koke** [comment]
Closing this one as it recovers fine
