### ISSUE TITLE
 Prepending text in a GB image block caption breaks GB editing

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/AztecEditor-Android#724]
### Expected
Adding text in front of the caption in a GB image block should not break the GB editing experience (`This block appears to have been modified externally.` placeholder).

### Observed
Adding text in front of the caption (`<figcaption>`) in a GB image block causes the `This block appears to have been modified externally.` placeholder to appear in GB, breaking the editing flow.

### Reproduced
1. Load the following html snippet in html mode:
```html
<!-- wp:image {"align":"center"} -->
<figure class="wp-block-image aligncenter">
  <img src="https://cldup.com/cXyG__fTLN.jpg" alt="Beautiful landscape" />
  <figcaption>If your theme supports it, you'll see the "wide" button on the image toolbar. Give it a try.
  </figcaption>
</figure>
<!-- /wp:image -->
```
2. Switch to visual mode and place the cursor in the very beginning of the caption (there might be a couple of spaces there so, make sure the cursor is at the start of the line)
3. Insert one or more characters
4. Switch to html mode and notice that the character(s) entered are inbetween the `<img>` and the `<figcaption>` elements. That is not valid for GB and causes the "modified externally" placeholder to appear.

#### Tested
Nexus 5X on Android v7.1.2, Aztec v1.3.6

**Comment by koke** [comment]
This one looks worse than the others, I'd expect the typed text to be inside `figcaption`. This results in bad HTML that will likely render badly on the frontend and Gutenberg doesn't know how to recover, even from Classic, dropping the edit.

How hard to fix would you expect this one to be?

**Comment by hypest** [comment]
> How hard to fix would you expect this one to be?

Haven't yet looked deep into it but from my first look it seems that it can be rather easy to fix. My plan is to try and get `figcaption` be implemented as a block span, following the HTML spec anyway.
