### ISSUE TITLE
Crash when deleting text

### ISSUE THREAD

**Issue by 0nko** [wordpress-mobile/AztecEditor-Android#749]
#### To reproduce

1. Open the demo app (in the emulator)
2. Select all text
3. Press the delete key
4. Notice the app crashes

**Comment by mzorz** [comment]
Unassigned myself as I couldn't do much progress with this one so far

**Comment by mzorz** [comment]
I was able to narrow down to issue to be only happening with image with captions:
If all the content there is is this:
```
[caption align="alignright"]<img src="https://examplebloge.files.wordpress.com/2017/02/3def4804-d9b5-11e6-88e6-d7d8864392e0.png" />Caption[/caption]
```

it breaks.

However an image alone, like this:

`<img src="https://examplebloge.files.wordpress.com/2017/02/3def4804-d9b5-11e6-88e6-d7d8864392e0.png" />`

doesn't break it.
