### ISSUE TITLE
How to use same Html.java to load html content in TextView

### ISSUE THREAD

**Issue by ranjitzade** [wordpress-mobile/AztecEditor-Android#794]
Basically, I'm using this editor as WYSIWYG to let users post data.
 But also I want to load the data that Html data, so instead of using internal HtmlTagHandler, I want to use the one that this library provided.

Is there a workaround for this?

**Comment by hypest** [comment]
👋 @ranjitzade , thanks for reaching out! If I understand correctly, what you're probably looking for is using the [Html.fromHtml()](https://github.com/wordpress-mobile/AztecEditor-Android/blob/d2492a835555c658581f495838cd0e5ba76bdb0b/aztec/src/main/java/org/wordpress/aztec/Html.java#L178) method, which is public and static. It will return a parsed string into Spanned.

Notice though that the span classes returned are highly tied with Aztec and I'm not sure how useful that will be in your case or any case outside Aztec itself, to be honest. That said, feel free to give it a try 🤞.

I will close this ticket as there is nothing to work on about it but, feel free to continue commenting here as see fit. Thanks!
