### ISSUE TITLE
How to change text color?

### ISSUE THREAD

**Issue by jrcacd** [wordpress-mobile/AztecEditor-Android#819]

**Comment by MrFuFuFu** [comment]
Any answer for that?

**Comment by hypest** [comment]
Aztec inherits from `EditText` and the `setTextColor()` method and friends are normally available to set the text color.

Will close this ticket now.

**Comment by MrFuFuFu** [comment]
![WechatIMG2](https://user-images.githubusercontent.com/6850766/69940325-e27da300-1546-11ea-87c4-2e15eac76acb.png)

What I mean is like this. Well, I have already done this in my app and maybe can submit a PR later.

**Comment by hypest** [comment]
Oh, I see. The way Aztec supports rendering individual colored words/characters is via inline CSS in the HTML input. See these tests for examples: https://github.com/wordpress-mobile/AztecEditor-Android/blob/develop/aztec/src/test/kotlin/org/wordpress/aztec/HtmlAttributeStyleColorTest.kt#L35-L42.

**Comment by jrcacd** [comment]
Can Aztec have a button with a pallete for choosing the color?

**Comment by hypest** [comment]
> Can Aztec have a button with a pallete for choosing the color?

From a design point of view, yes, I think it could. From the implementation side, I think it could take some effort for those who'll implemented it to hook up the relevant Span classes to support adding/setting/removing while in editing mode.

**Comment by jrcacd** [comment]
> > Can Aztec have a button with a pallete for choosing the color?
> 
> From a design point of view, yes, I think it could. From the implementation side, I think it could take some effort for those who'll implemented it to hook up the relevant Span classes to support adding/setting/removing while in editing mode.

That would be awesome.

**Comment by duyvt88** [comment]
@MrFuFuFu Could you please submit your code? I would like to have that capability. Or could you please give me a guide to do it?
Many Thanks,

**Comment by MrFuFuFu** [comment]
@duyvt88  thanks for asking. I did somehow managed to change the color, but somehow, it doesn't work as I expected. I'm now using https://github.com/wasabeef/richeditor-android it works great and easy to manage.

**Comment by duyvt88** [comment]
> @duyvt88 thanks for asking. I did somehow managed to change the color, but somehow, it doesn't work as I expected. I'm now using https://github.com/wasabeef/richeditor-android it works great and easy to manage.
@MrFuFuFu Thanks for your reply. I will try it now.
