### ISSUE TITLE
Can't properly insert text on Android 7

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/AztecEditor-Android#854]
This is related to https://github.com/wordpress-mobile/AztecEditor-Android/issues/853 and it's very noticeable on my Nexus 5x running Android 7.1.

Video here: https://cloudup.com/c9B1MVYh9lz (I was trying to type "Hello There").

Introduced since `v1.3.29`. I'm kind of surprised that we've not caught it during tests, maybe it's a problem on my device only?  
I just tested 2 previous versions, and those worked fine on my testing device. (The other testing device of mine, running Android 9 with Samsung keyboard, is not affected by this problem).

cc @marecar3 @khaykov  @hypest

**Comment by marecar3** [comment]
Thanks, @daniloercoli!
I will see with @khaykov where could be the problem.

**Comment by marecar3** [comment]
It seems that both this and #853 are exposed because of this change: https://github.com/wordpress-mobile/AztecEditor-Android/pull/838/files#diff-7ca71cd1f009ab8438e0901205001b14R455-R465

**Comment by marecar3** [comment]
>Introduced since v1.3.29. I'm kind of surprised that we've not caught it during tests
Hey @daniloercoli, as a reviewer on that PR, I am taking full responsibility for those two bugs.

I was testing with the less Post `content` which test case didn't expose this kind of bug.
Now tested on Nexus 5x, 8.1 Android, and manage to reproduce it with full example content.

**Comment by daniloercoli** [comment]
>> Introduced since v1.3.29. I'm kind of surprised that we've not caught it during tests

>> Hey @daniloercoli, as a reviewer on that PR, I am taking full responsibility for those two bugs.

I think the responsibility should be shared among all of us, not only you @marecar3 , since we all are using the editor, and it's now included in GB mobile. 

Btw, I encourage you all to run `app->tests` on your PRs, since also tests started failing in .29. That would have been an indicator that something was going off.

**Comment by marecar3** [comment]
>Btw, I encourage you all to run app->tests on your PRs, since also tests started failing in .29. That would have been an indicator that something was going off.

Not sure why tests passed on this PR with the last commit: https://github.com/wordpress-mobile/AztecEditor-Android/pull/838/commits ?

**Comment by designsimply** [comment]
fwiw, I tested with WPAndroid alpha-190 (13.3 alpha) on Pixel 3 Android 10 and didn't spot any lag at all with the demo content pasted in 3x. ([2min](https://cloudup.com/cNxhlLa7xlA))

**Comment by designsimply** [comment]
Spotted one report of this in a 1-star play store review and am noting it here for reference:

> This app literally glitches like it's part of the matrix and wont let you type like that's wack it's a blog it should let you type! 

* Oct 3, 2019 at 3:14 PM
* App version 776 (13.2)
* OS Android 8.1

**Comment by designsimply** [comment]
Found one other possible case of a user report of this:

> There is a massive lag when creating a post.

* Reported on Apr 15 23:56
* WPAndroid 12.1.2
* OS: Android version 7.0 
* Device: Samsung Galaxy Tab S2

<sup>(internal reference: p4a5px-2om-p2#comment-9768)</sup>
