### ISSUE TITLE
onImeBack() is sometimes not called when expected

### ISSUE THREAD

**Issue by ghutchins56** [wordpress-mobile/AztecEditor-Android#862]
### Expected
I expect onBackIme() to always be called when touching device Back button after touching  AztecToolbar

### Observed
After touching expand or collapse button in AztecToolbar, onBackIme() is not always called

### Reproduced
1. Touch AztecText
2. Touch expand or collapse button in AztecToolbar
3. Touch device Back button

#### Tested
SAMSUNG-SM-G900A on Android 6.0.1 with Aztec 1.3.33

**Comment by ghutchins56** [comment]
This also happens sometimes for toolbar buttons other than expand or collapse.

**Comment by ercanduman** [comment]
@ghutchins56 I have similar problem, did you figure out the reason?

**Comment by ercanduman** [comment]
I had the issue when implemented the library in gradle as
```
    // Aztec Editor
    api ('com.github.wordpress-mobile.WordPress-Aztec-Android:aztec:v1.3.36')
```
changing to 
```
    // Aztec Editor
    implementation project(':aztec')
```
as used in demo app, solved the issue for me. Thanks for this great library, appreciated it.
