### ISSUE TITLE
Aztec: Add image icon is "x" instead of "+"

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/AztecEditor-Android#908]
### Expected
The "add" image icon is "+"  and it animates into "x" after the user clicks on it. 

### Observed
The "add" image icon  is "x" even before the user clicks on it.

### Reproduced
1. Open Aztec
2. Notice the icon is "x" instead of "+"

<img width="489" alt="Screenshot 2020-05-22 at 11 26 11" src="https://user-images.githubusercontent.com/2261188/82659950-c7ecd280-9c29-11ea-9783-af0fdb100c39.png">

**Comment by hypest** [comment]
Using `git bisect` I've pinpointed the start of the regression to [this PR](https://github.com/wordpress-mobile/AztecEditor-Android/pull/900). @anitaa1990 , can you have a look? It'd be good if we fix this regression soon now that we spotted it. Thanks!

**Comment by anitaa1990** [comment]
Thanks for the ping @hypest! I'll take a look today!

**Comment by anitaa1990** [comment]
I have opened a [PR](https://github.com/wordpress-mobile/AztecEditor-Android/pull/909) with a fix. Should I create a new release in Aztec and open a draft PR in Woo and WP with this fix?

**Comment by hypest** [comment]
> Should I create a new release in Aztec and open a draft PR in Woo and WP with this fix?

Hey Anitaa, yeap, that'd be great, thanks! cc @SergioEstevao, @mchowning since the Aztec version bump will need to be included in the gutenberg-mobile too, so the WPAndroid build succeeds.
