### ISSUE TITLE
BackgroundColorSpan support?

### ISSUE THREAD

**Issue by arctouch-felipevaladares** [wordpress-mobile/AztecEditor-Android#910]
Does the lib support BackgroundColorSpan? i need to create a custom toolbar and one of the options should be to paint the text background like this:
![image](https://user-images.githubusercontent.com/59581302/82846196-10242300-9ebe-11ea-8c47-fddbd6be1b02.png)

**Comment by felipevaladares** [comment]
i did by my self on this PR https://github.com/wordpress-mobile/AztecEditor-Android/pull/911
