### ISSUE TITLE
Can the library be fully migrated to AndroidX?

### ISSUE THREAD

**Issue by ygnessin** [wordpress-mobile/AztecEditor-Android#933]
### Expected
First of all, thank you for maintaining such a wonderful library!

For any version past [v1.3.28](https://github.com/wordpress-mobile/AztecEditor-Android/releases/tag/v1.3.28) I would expect this library to be migrated to AndroidX, and therefore not to require jetifier to be enabled.

### Observed
When using the [can-i-drop-jetifier](https://github.com/plnice/can-i-drop-jetifier) gradle plugin, I receive the following result:

```
Cannot drop Jetifier due to following external dependencies:

* com.github.wordpress-mobile.WordPress-Aztec-Android:aztec:v1.3.45
```

### Reproduced
1. Have this in your gradle file: 
```
implementation "com.github.wordpress-mobile.WordPress-Aztec-Android:aztec:v1.3.45"
```
2. Set up [can-i-drop-jetifier](https://github.com/plnice/can-i-drop-jetifier) according to the readme
3. Run `./gradlew -Pandroid.enableJetifier=false canIDropJetifier`
4. Observe the error message above

### Other

I noticed in the [build.gradle](https://github.com/wordpress-mobile/AztecEditor-Android/blob/develop/aztec/build.gradle) file a couple dependencies that may or may not be contributing to this issue:
```
vectorDrawables.useSupportLibrary = true
...
implementation 'androidx.legacy:legacy-support-v4:1.0.0'
```
Hopefully that helps. Thanks again for the wonderful library!

**Comment by ygnessin** [comment]
I was able to use the plugin's `verbose` setting to find a little more info:

```
* com.github.wordpress-mobile.WordPress-Aztec-Android:aztec:v1.3.45
  \-- org.wordpress:utils:1.21
   \-- com.android.support:support-v13:27.1.1
  \-- org.wordpress:utils:1.21
   \-- com.android.support:design:27.1.1
  \-- org.wordpress:utils:1.21
   \-- com.android.support:recyclerview-v7:27.1.1
```

Hopefully this helps you get to the bottom of it!

**Comment by ygnessin** [comment]
In the meantime, I have found a work-around for this by exposing a direct dependency to `org.wordpress:utils`:
```gradle
implementation "com.github.wordpress-mobile.WordPress-Aztec-Android:aztec:v1.3.45"
implementation "org.wordpress:utils:1.29"
```
These seems to solve the problem for me for now.

**Comment by oguzkocer** [comment]
@ygnessin Thank you for reporting this issue. We have dropped jetifier in https://github.com/wordpress-mobile/AztecEditor-Android/pull/946. I am sorry it took so long to be addressed.
