### ISSUE TITLE
Failed Build

### ISSUE THREAD

**Issue by Kodak1234** [wordpress-mobile/AztecEditor-Android#951]
The latest release build is failing, check jitpack.io. So unable to import project into android studio

**Comment by Kodak1234** [comment]
![image](https://user-images.githubusercontent.com/17802465/150647278-9f059a18-01be-4b5b-ade1-73ad9c4fb221.png)

**Comment by hypest** [comment]
Thanks for reporting!

Here's the build log on the JitPack job:

```
* What went wrong:
Execution failed for task ':picasso-loader:prepareToPublishToS3'.
> Either tagName or both branch name and sha1 command line arguments needs to be provided!
  Example usages:
  --tag-name={tag-name}
  --pull-request-number={pull-request-number} --branch-name={branch-name} --sha1={sha1-commit-hash}
  --branch-name={branch-name} --sha1={sha1-commit-hash}
```

👋 @oguzkocer , would you have the chance to have a look? Looks like a failure that happens on multiple (older) releases, not sure if this is due to some recent change or not. Thanks!

**Comment by hypest** [comment]
My ping above probably didn't go through (it was erroneously left inside the code block) so, let me add this new comment with it. 👋 @oguzkocer , can you have a look to this ticket? Thanks!

**Comment by oguzkocer** [comment]
@hypest You're correct, I didn't receive the previous ping. We no longer use Jitpack as we started publishing our artifacts to our S3 Maven through a Buildkite job instead. I created a PR to update the integration instructions in `README`: #954

@Kodak1234 If you add the following maven url to your repositories, you should be able to fetch the latest artifacts:

```gradle
repositories {
    maven { url "https://a8c-libs.s3.amazonaws.com/android" }
}
``` 

Please feel free to ping me if you have any issues.

**Comment by Kodak1234** [comment]
I'm still unable to pull the latest artifacts. 
```build.gradle
allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://a8c-libs.s3.amazonaws.com/android" }
        maven { url 'https://jitpack.io' }
    }
}
```

**Comment by oguzkocer** [comment]
@Kodak1234 ~Which version are you trying to fetch?~ Please note that only the latest few versions are available in the S3 maven repository, `v1.5.4` being one of them.

~If you can share the line where you're adding the dependency, that'd be helpful.~

Edit: The issue was most likely because of the change in artifact path which I've commented on separately [below](https://github.com/wordpress-mobile/AztecEditor-Android/issues/951#issuecomment-1028589657). Just making this edit, so it points to the correct comment.

**Comment by oguzkocer** [comment]
@Kodak1234 I forgot that we changed the path of the artifact. Can you update your dependency as below and try again?

```gradle
dependencies {
    api "org.wordpress:aztec:v1.5.4"
}
```

Sorry about that confusion!

**Comment by Kodak1234** [comment]
@oguzkocer Please can you guys write a documentation on the best way to implement this editor in recyclerview, using a simple textview does not render all the spans properly.

**Comment by oguzkocer** [comment]
@Kodak1234 I unfortunately don't have experience working with the library, but I'll bring it up internally to see if anyone who has experience have the bandwidth to write such a documentation.

In the meantime, your best best might be to look into how it's used in other WordPress projects. [Here is the module it's used in the Gutenberg project](https://github.com/WordPress/gutenberg/tree/trunk/packages/react-native-aztec) and [here is the one for WordPress-Android](https://github.com/wordpress-mobile/WordPress-Android/tree/trunk/libs/editor). In WordPress-Android, it might be used in other modules as well, so you might want to do a full search in the project.

I'll follow up about the internal discussion next week. Hope that helps!

**Comment by hypest** [comment]
> Please can you guys write a documentation on the best way to implement this editor in recyclerview

👋 @Kodak1234, there doesn't seem to be available bandwidth from the main maintainers at the moment to dive into this request, sorry 😞 . That said, the links @oguzkocer shared above can be a good resource to check.

> using a simple textview does not render all the spans properly.

I'd suggest to open a new ticket to focus on the specific usecase, ideally including links to code that can be reviewed. Aztec has been designed to be a replacement to an EditText, and shouldn't need any special handling to make it work in a RecyclerView. I could be forgetting something though so yeah, best if, in a separate ticket, you can provide a code example that fails to render the spans. Thanks!
